Repository RackReaver/AVMP, pull requests merged in 2022-01, with the labels that each got.

#10 chore: :arrow_up: Bump jira package version
  avmp/core/wrapper.py
  poetry.lock
  pyproject.toml
Labels: chore

#13 fix: :bug: Key change for parent ticket
  avmp/core/wrapper.py
Labels: bug

#14 docs: :memo: Change logo url
  README.md
Labels: documentation

#15 docs: :page_facing_up: Update and reformat license
  LICENSE
Labels: documentation

#18 feat: Add example tenable asv process
  examples/static_process_configs/readme.md
  examples/static_process_configs/tenable_asv_process.json
Labels: enhancement

#19 docs: 📝 Ticket buckets for engineer time tracking
  examples/static_process_configs/readme.md
  examples/static_process_configs/ticket_buckets_for_engineer_time_tracking.json
Labels: documentation

#22 docs: 📝 Fix spelling error on README.md
  README.md
Labels: chore
